-- Supabase Database Export
-- Generated on 2026-05-12

-- 1. Create Enums
DO $$ BEGIN
    CREATE TYPE public.section_type AS ENUM ('personal_info', 'experience', 'education', 'blog', 'project');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.user_role AS ENUM ('super_admin', 'admin', 'editor', 'viewer');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.locale_type AS ENUM ('en', 'hi');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE public.theme_mode AS ENUM ('system', 'light', 'dark');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Create Functions
CREATE OR REPLACE FUNCTION public.current_user_role()
 RETURNS public.user_role
 LANGUAGE sql
 STABLE
AS $function$
  select coalesce(
    (select role::public.user_role from public.user_roles where user_id = auth.uid()),
    'viewer'::public.user_role
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_super_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select public.current_user_role() = 'super_admin';
$function$;

CREATE OR REPLACE FUNCTION public.is_admin_or_higher()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select public.current_user_role() in ('super_admin', 'admin');
$function$;

CREATE OR REPLACE FUNCTION public.can_edit_content()
 RETURNS boolean
 LANGUAGE sql
 STABLE
AS $function$
  select public.current_user_role() in ('super_admin', 'admin', 'editor');
$function$;

-- 3. Create Tables
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id),
    name text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.content_entries (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    section public.section_type NOT NULL,
    locale public.locale_type DEFAULT 'en'::public.locale_type NOT NULL,
    slug text,
    seo_title text,
    seo_description text,
    seo_keywords text[],
    og_image text,
    name text,
    title text,
    contact_info text,
    email text,
    linkedin text,
    summary text,
    skills text[],
    company text,
    position text,
    duration text,
    responsibilities text,
    degree text,
    institution text,
    year integer,
    grade text,
    blog_title text,
    blog_excerpt text,
    blog_content text,
    blog_tags text[],
    published_at timestamp with time zone,
    project_name text,
    project_description text,
    project_url text,
    project_images text[],
    project_tags text[],
    approved boolean DEFAULT true,
    created_by uuid REFERENCES auth.users(id),
    updated_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp with time zone,
    version integer DEFAULT 1,
    "order" integer DEFAULT 0,
    project_icon text,
    team_size integer,
    role text,
    specialization text,
    CONSTRAINT content_entries_year_check CHECK (year IS NULL OR year >= 1900)
);

CREATE TABLE IF NOT EXISTS public.content_entry_versions (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    entry_id uuid REFERENCES public.content_entries(id),
    version integer NOT NULL,
    data jsonb NOT NULL,
    changed_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    actor_id uuid REFERENCES auth.users(id),
    action text NOT NULL,
    entity text NOT NULL,
    entity_id text,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    email text NOT NULL UNIQUE,
    user_id uuid REFERENCES auth.users(id),
    role text DEFAULT 'viewer'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sections (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    section_type text NOT NULL UNIQUE,
    is_visible boolean DEFAULT true,
    "order" integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.skills (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    category text NOT NULL,
    "order" integer DEFAULT 0,
    is_visible boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.social_links (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform text NOT NULL,
    label text NOT NULL,
    url text NOT NULL,
    is_visible boolean DEFAULT true,
    "order" integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hero_config (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    greeting text DEFAULT 'Hello! I''m'::text NOT NULL,
    subtitle text DEFAULT 'A passionate Senior Android Developer'::text NOT NULL,
    tagline text DEFAULT 'Building scalable, high-performance mobile applications using modern Android architecture and practices.'::text NOT NULL,
    cta_text text DEFAULT 'Download Resume'::text NOT NULL,
    cta_link text DEFAULT '/Raj_Vaibhav_Rai_Android.pdf'::text,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hero_slider_titles (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    "order" integer DEFAULT 0,
    is_visible boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hero_bubbles (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label text NOT NULL,
    icon text DEFAULT '🔧'::text NOT NULL,
    color text DEFAULT '#00D9FF'::text NOT NULL,
    pos_x text DEFAULT '0px'::text,
    pos_y text DEFAULT '0px'::text,
    is_visible boolean DEFAULT true,
    "order" integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.certificates (
    id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    issuer text,
    issue_date date,
    image_url text,
    "order" integer DEFAULT 0,
    is_visible boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 4. Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_entry_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_slider_titles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hero_bubbles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- 5. Policies
DROP POLICY IF EXISTS delete_content ON public.content_entries;
CREATE POLICY delete_content ON public.content_entries FOR UPDATE TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS update_content ON public.content_entries;
CREATE POLICY update_content ON public.content_entries FOR UPDATE TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS create_content ON public.content_entries;
CREATE POLICY create_content ON public.content_entries FOR INSERT TO authenticated WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_content ON public.content_entries;
CREATE POLICY public_read_content ON public.content_entries FOR SELECT USING ((deleted_at IS NULL) AND ((approved = true) OR ((auth.uid() IS NOT NULL) AND public.can_edit_content())));

DROP POLICY IF EXISTS audit_read_admins ON public.audit_logs;
CREATE POLICY audit_read_admins ON public.audit_logs FOR SELECT TO authenticated USING (public.is_admin_or_higher());

DROP POLICY IF EXISTS users_read_own_role ON public.user_roles;
CREATE POLICY users_read_own_role ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS certificates_full_access ON public.certificates;
CREATE POLICY certificates_full_access ON public.certificates FOR ALL USING (auth.role() = 'authenticated'::text) WITH CHECK (auth.role() = 'authenticated'::text);

DROP POLICY IF EXISTS certificates_public_read ON public.certificates;
CREATE POLICY certificates_public_read ON public.certificates FOR SELECT USING (is_visible = true);

DROP POLICY IF EXISTS admin_all_sections ON public.sections;
CREATE POLICY admin_all_sections ON public.sections FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_sections ON public.sections;
CREATE POLICY public_read_sections ON public.sections FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_all_skills ON public.skills;
CREATE POLICY admin_all_skills ON public.skills FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_skills ON public.skills;
CREATE POLICY public_read_skills ON public.skills FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_all_social ON public.social_links;
CREATE POLICY admin_all_social ON public.social_links FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_social ON public.social_links;
CREATE POLICY public_read_social ON public.social_links FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_all_hero_config ON public.hero_config;
CREATE POLICY admin_all_hero_config ON public.hero_config FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_hero_config ON public.hero_config;
CREATE POLICY public_read_hero_config ON public.hero_config FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_all_slider ON public.hero_slider_titles;
CREATE POLICY admin_all_slider ON public.hero_slider_titles FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_slider ON public.hero_slider_titles;
CREATE POLICY public_read_slider ON public.hero_slider_titles FOR SELECT USING (true);

DROP POLICY IF EXISTS admin_all_bubbles ON public.hero_bubbles;
CREATE POLICY admin_all_bubbles ON public.hero_bubbles FOR ALL TO authenticated USING (public.can_edit_content()) WITH CHECK (public.can_edit_content());

DROP POLICY IF EXISTS public_read_bubbles ON public.hero_bubbles;
CREATE POLICY public_read_bubbles ON public.hero_bubbles FOR SELECT USING (true);

-- 6. Initial Data
INSERT INTO public.user_roles (id, email, user_id, role) 
VALUES ('890811e7-db7f-44af-999b-602a938ff79c', 'rvrai1998@gmail.com', 'e518468b-dd35-4d33-8795-1d4bdae886f0', 'admin')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.sections (id, name, section_type, is_visible, "order") VALUES
(1, 'Hero', 'hero', true, 1),
(2, 'About', 'about', true, 2),
(5, 'Projects', 'projects', true, 3),
(3, 'Experience', 'experience', true, 4),
(4, 'Skills', 'skills', true, 5),
(6, 'Education', 'education', true, 6),
(7, 'Contact', 'contact', true, 7),
(8, 'Footer', 'footer', true, 8),
(9, 'Certificates', 'certificates', false, 7)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.skills (id, name, category, "order", is_visible) VALUES
(1, 'Java', 'Core', 1, true),
(2, 'Kotlin', 'Core', 2, true),
(3, 'Jetpack Compose', 'Android', 3, true),
(4, 'Material Design', 'Android', 4, true),
(5, 'MVVM', 'Architecture', 5, true),
(6, 'Solid Principles', 'Architecture', 6, true),
(7, 'Clean Architecture', 'Architecture', 7, true),
(8, 'Coroutine', 'Concurrency', 8, true),
(9, 'Flow', 'Concurrency', 9, true),
(10, 'Dagger / Hilt', 'DI', 10, true),
(11, 'Rest API Integration', 'Networking', 11, true),
(12, 'Retrofit', 'Networking', 12, true),
(13, 'Room', 'Database', 13, true),
(14, 'DataStore', 'Database', 14, true),
(15, 'Firebase', 'Cloud', 15, true),
(16, 'GIT / Github', 'Tools', 16, true),
(17, 'JIRA / Figma', 'Tools', 17, true),
(18, 'Agile / Scrum', 'Workflow', 18, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.social_links (id, platform, label, url, is_visible, "order") VALUES
(1, 'linkedin', 'LinkedIn', 'https://linkedin.com/in/rvrai', true, 1),
(2, 'github', 'GitHub', 'https://github.com/rvrai', true, 2),
(3, 'email', 'rvrai1998@gmail.com', 'mailto:rvrai1998@gmail.com', true, 3)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hero_config (id, greeting, subtitle, tagline, cta_text, cta_link) VALUES
(1, 'Hello! I''m', 'A passionate Senior Android Developer', 'Building scalable, high-performance mobile applications using modern Android architecture and practices.', 'Download Resume', '/Raj_Vaibhav_Rai_Android.pdf')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hero_slider_titles (id, title, "order", is_visible) VALUES
(1, 'ANDROID', 1, true),
(2, 'PROGRAMMER', 2, true),
(3, 'DEVELOPER', 3, true),
(4, 'ENGINEER', 4, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hero_bubbles (id, label, icon, color, pos_x, pos_y, is_visible, "order") VALUES
(1, 'Kotlin', 'Kt', '#7F52FF', '-300px', '-200px', true, 1),
(2, 'Android', '🤖', '#3DDC84', '280px', '-280px', true, 2),
(3, 'Jetpack', '📦', '#4285F4', '-380px', '60px', true, 3),
(4, 'Firebase', '🔥', '#FFCA28', '400px', '-40px', true, 4),
(5, 'Java', '☕', '#f89820', '-300px', '250px', true, 5),
(6, 'Room DB', '🗄️', '#00B0FF', '310px', '230px', true, 6),
(7, 'Hilt/Dagger', '🗡️', '#D81B60', '-130px', '360px', true, 7),
(8, 'Figma', '🎨', '#F24E1E', '150px', '380px', true, 8),
(9, 'Git', '◆', '#f34f29', '0px', '480px', true, 9)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.content_entries (id, section, locale, name, title, contact_info, email, linkedin, summary, skills, company, position, duration, responsibilities, degree, institution, year, grade, project_name, project_description, project_url, project_tags, approved, "order") VALUES
('fc6ba557-105a-4ab9-b098-5f487bc4673b', 'personal_info', 'en', 'Raj Vaibhav Rai', 'Senior Android Developer', '+91-8423914735', 'rvrai1998@gmail.com', 'linkedin.com/in/rvrai', 'Senior Android Developer with 5+ years of experience building scalable, high-performance mobile applications using Kotlin and Java. Expertise in MVVM, Clean Architecture, Coroutines, Flow, Jetpack, Room, Hilt, Firebase, REST APIs, and modern Android development practices.', ARRAY['Java','Kotlin','Jetpack Compose','Material Design','MVVM','Solid Principles','Clean Architecture','Coroutine','Flow','Dagger / Hilt','Rest API Integration','Retrofit','Room','DataStore','Firebase','GIT / Github','JIRA / Figma','Agile / Scrum'], NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 0),
('c2d09135-c4fc-407d-9bb4-4b18e5665afa', 'experience', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rupyz Fintech Private Limited', 'Software Developer', 'May 2024 - Present', 'Developed and maintained scalable Android applications using Kotlin and Java.\nImplemented MVVM architecture with Room, Hilt, Coroutines, and Flow.\nImproved performance, stability, and feature scalability across product modules.\nCollaborated with product, design, and QA teams in agile delivery cycles.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 0),
('11f0bd22-eb1c-49ab-be62-c1da53b41cd3', 'experience', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Techahead Software Private Limited', 'Android Developer', 'Apr 2023 - May 2024', 'Built advanced Android features improving user engagement and app performance.\nWorked on modern Android components including DataStore and Flow.\nContributed to scalable architecture and optimized code quality.\nCoordinated with cross-functional teams for production releases.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 0),
('2aeb68f4-64a6-43c5-b6db-14b880307dfe', 'experience', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CEDCOSS Technologies Private Limited', 'Android Developer', 'Aug 2020 - Apr 2023', 'Led Android development using MVVM, Room, Firebase, Dagger/Hilt, and Jetpack.\nIntegrated payment SDKs, search capabilities, and third-party services.\nReduced crash rates by 80% through optimization and debugging.\nMentored junior developers and contributed to architectural decisions.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 0),
('af46e6b9-5f07-4ca4-8f93-ebeef7092628', 'experience', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Coding Brains', 'Android Developer', 'Sep 2019 - Aug 2020', 'Experienced in bug fixing, optimization, and new feature development.\nCapable of end-to-end app creation, including UI/UX design.\nAdept at client communication for delivering desired app functionality.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 0),
('ef3cf250-0d85-4ab5-9ca6-f573abe34227', 'education', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B.Tech/B.E.', 'ITM School of Management Lucknow', 2022, '7.4/10', NULL, NULL, NULL, NULL, true, 0),
('e84c433c-7fb7-43b7-91f7-4c01c5c68204', 'education', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '12th', 'CBSE Board', 2015, '60-64.9%', NULL, NULL, NULL, NULL, true, 0),
('5a7ade4c-9b88-4b9d-9b31-7db80d006f0f', 'education', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '10th', 'CBSE Board', 2013, '65-69.9%', NULL, NULL, NULL, NULL, true, 0),
('2cab69af-7dda-4d96-b884-d36fc829f1c6', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HappyMob', 'A platform for business to register and search local business.', NULL, ARRAY['Android','Kotlin'], true, 0),
('c7c5d3c1-073a-4808-a215-1563e3524a5b', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Kido Protect Parental Control', 'Parental control application for screen monitoring and restrictions.', '#', ARRAY['Kotlin','Jetpack','Firebase'], true, 0),
('d1ca9f15-0544-46ec-bd2f-425e9cd1a9c3', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DolledUp', 'Social-commerce Android application integrating content and shopping.', '#', ARRAY['Kotlin','MVVM','Firebase','REST APIs'], true, 0),
('f49d5a28-6099-4fa5-894f-9e30b79e52af', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Magenative Shopify App', 'Mobile commerce builder for Shopify stores.', '#', ARRAY['Java','Kotlin','APIs','Push Notifications'], true, 0),
('dac6c67f-4455-40f2-8007-c15f9653319b', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Magenative Woocommerce App', 'Sophisticated native Android solution for WooCommerce with dynamic experience. Seamlessly synchronizes products and categories.', '#', ARRAY['Java','Kotlin','WooCommerce API'], true, 0),
('6d2c20d4-2e25-461c-991d-373a43fb4d6b', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Classical Archive', 'Premier platform for classical music enthusiasts worldwide. Curated collection, seamless streaming.', '#', ARRAY['Android','Streaming'], true, 0),
('c8af6a1e-540b-47a4-b301-2ca98738349e', 'project', 'en', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ERP base Attendance system', 'Freelancing project for third party to be introduced to government.', NULL, ARRAY['Android','ERP'], true, 0)
ON CONFLICT (id) DO NOTHING;
